### ISSUE TITLE
Component files empty causing ddsim crash

### ISSUE THREAD

**Issue by rete** [AIDASoft/DD4hep#567]
- OS version: CentOS 7
 - uname: `Linux naf-ilc-gpu01.desy.de 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
 - Compiler version: GCC 7.3.0
 - DD4hep version: v01-10
 - ROOT version: v6.18.04
 - Geant4 version: v10.5.1

# Compiling the software

Using CVMFS facility:
```shell
# gcc 7.3.0
source /cvmfs/sft.cern.ch/lcg/contrib/gcc/7.3.0/x86_64-centos7/setup.sh
# CMake 3.14.3
export PATH=/cvmfs/sft.cern.ch/lcg/releases/CMake/3.14.3-34449/x86_64-centos7-gcc7-opt/bin:$PATH
# Python 2.7, compatible with gcc 7
export PATH=/cvmfs/sft.cern.ch/lcg/releases/Python/2.7.15-6f88d/x86_64-centos7-gcc7-opt/bin:$PATH
export LD_LIBRARY_PATH=/cvmfs/sft.cern.ch/lcg/releases/Python/2.7.15-6f88d/x86_64-centos7-gcc7-opt/lib:$LD_LIBRARY_PATH
```

Compiling ROOT with:
```shell
# get the software
git clone https://github.com/root-project/root.git
cd root; git checkout v6-18-04
mkdir build-root; cd build-root
# configure and build
cmake -DCMAKE_CXX_STANDARD=17 -Dgenvector=ON -Dgsl_shared=ON -Dimt=ON -Droot7=ON -DCMAKE_INSTALL_PREFIX=$PWD/../install ..
make install
```

Compiling Geant4:
```shell
# get the software
git clone https://github.com/Geant4/geant4.git
cd geant4; git checkout v10.5.1
mkdir build-geant; cd build-geant
# configure and compile
cmake -DGEANT4_BUILD_CXXSTD=17 -DGEANT4_INSTALL_DATA=ON -DCMAKE_INSTALL_PREFIX=$PWD/../install -DGEANT4_USE_GDML=ON -DXERCESC_ROOT_DIR=/path/to/XercesC  ..
```

Compiling DD4hep:
```shell
source /path/to/root/install/bin/thisroot.sh
source /path/to/geant4/install/bin/geant4.sh
# get the software
git clone https://github.com/AIDASoft/DD4hep.git
cd DD4hep; git checkout v01-10
mkdir build-dd4hep; cd build-dd4hep
# configure and compile
cmake -DDD4HEP_USE_GEANT4=ON -DDD4HEP_USE_LCIO=OFF -DDD4HEP_USE_BOOST=ON -DCMAKE_CXX_STANDARD=17 ..
```

# The issue

The compilation goes until the end, but shows these errors messages (only for the one listing below)

```
--  *** Gaudi listcomponents: Generate map for libDDG4Legacy.so ...
--  *** MakeGaudiMap.cmake run command : /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/build-v01-10/bin/listcomponents -o libDDG4Legacy.components libDDG4Legacy.so
                 WORKING_DIRECTORY /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/build-v01-10/lib
fatal error: malformed or corrupted AST file: 'could not decompress embedded file contents: zlib error: Z_STREAM_ERROR'

--  *** Gaudi listcomponents: Generate map for libDDG4Python.so ...
--  *** MakeGaudiMap.cmake run command : /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/build-v01-10/bin/listcomponents -o libDDG4Python.components libDDG4Python.so
                 WORKING_DIRECTORY /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/build-v01-10/lib
fatal error: malformed or corrupted AST file: 'could not decompress embedded file contents: zlib error: Z_STREAM_ERROR'

--  *** Gaudi listcomponents: Generate map for libDDG4LCIO.so ...
--  *** MakeGaudiMap.cmake run command : /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/build-v01-10/bin/listcomponents -o libDDG4LCIO.components libDDG4LCIO.so
                 WORKING_DIRECTORY /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/build-v01-10/lib
fatal error: malformed or corrupted AST file: 'could not decompress embedded file contents: zlib error: Z_STREAM_ERROR'

--  *** Gaudi listcomponents: Generate map for libDDG4Plugins.so ...
--  *** MakeGaudiMap.cmake run command : /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/build-v01-10/bin/listcomponents -o libDDG4Plugins.components libDDG4Plugins.so
                 WORKING_DIRECTORY /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/build-v01-10/lib 
fatal error: malformed or corrupted AST file: 'could not decompress embedded file contents: zlib error: Z_STREAM_ERROR'
```

As a consequence the corresponding component files are empty and the `ddsim` related CMake tests are failing.
I get the same messages if I compile `lcgeo` and can't run any `ddsim` job.

I tried to run the `listcomponent` program after compilation, it shows the same error, so I can't re-generate these files after compilation too.

From the error message, I have strong suspicions on my Geant4 build or on the different software compatibility.

Thanks for your help.

Related thread: https://github.com/iLCSoft/iLCInstall/pull/68

**Comment by petricm** [comment]
- Is is really only the DDG4 libraries that are not working or all?
 - Why are you building `libDDG4LCIO` if you have `-DDD4HEP_USE_LCIO=OFF`?
 - Are these problems present with master?

**Comment by rete** [comment]
```
- Is is really only the DDG4 libraries that are not working or all?
```
It looks like yes.
```
- Why are you building libDDG4LCIO if you have -DDD4HEP_USE_LCIO=OFF?
```
I tried both with and without and observed the same issue, so I also reported it.
```
- Are these problems present with master?
```
I don't know, I didn't tested it. I'll try and come back to you

**Comment by petricm** [comment]
I really don't have enough information, but I guess it's that you don't build geant4 with `-DGEANT4_BUILD_TLS_MODEL=global-dynamic`, this should become clear when you try to build from master, as there is a check now.

**Comment by petricm** [comment]
and also I think you should use `-DGEANT4_BUILD_CXXSTD=c++17` to set the geant4 standard and not invoke the `DCMAKE_CXX_STANDARD=17`, this might have unforeseen consequences.

**Comment by rete** [comment]
master doesn't compile:

```shell
cmake -DDD4HEP_USE_GEANT4=ON -DDD4HEP_USE_LCIO=OFF -DDD4HEP_USE_BOOST=ON -DCMAKE_CXX_STANDARD=17 ../master
make install
# ...
[  0%] Building CXX object GaudiPluginService/CMakeFiles/DD4hepGaudiPluginMgr.dir/src/PluginServiceV2.cpp.o
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/src/PluginServiceV2.cpp: In member function ‘void DD4hep_Flavor::PluginService::v2::Details::Registry::initialize()’:
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/src/PluginServiceV2.cpp:177:65: error: ‘begin’ was not declared in this scope
                 for ( auto& p : fs::directory_iterator( dirName ) ) {
                                                                 ^
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/src/PluginServiceV2.cpp:177:65: note: suggested alternative:
In file included from /cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/string:51:0,
                 from /cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/stdexcept:39,
                 from /cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/array:39,
                 from /cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/tuple:39,
                 from /cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/functional:54,
                 from /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/Gaudi/Details/PluginServiceDetailsV2.h:29,
                 from /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/Gaudi/PluginServiceV2.h:17,
                 from /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/Gaudi/PluginService.h:20,
                 from /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/src/PluginServiceV2.cpp:15:
/cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/bits/range_access.h:105:37: note:   ‘std::begin’
   template<typename _Tp> const _Tp* begin(const valarray<_Tp>&);
                                     ^~~~~
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/src/PluginServiceV2.cpp:177:65: error: ‘end’ was not declared in this scope
                 for ( auto& p : fs::directory_iterator( dirName ) ) {
                                                                 ^
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/src/PluginServiceV2.cpp:177:65: note: suggested alternative:
In file included from /cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/string:51:0,
                 from /cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/stdexcept:39,
                 from /cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/array:39,
                 from /cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/tuple:39,
                 from /cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/functional:54,
                 from /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/Gaudi/Details/PluginServiceDetailsV2.h:29,
                 from /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/Gaudi/PluginServiceV2.h:17,
                 from /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/Gaudi/PluginService.h:20,
                 from /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/src/PluginServiceV2.cpp:15:
/cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/bits/range_access.h:107:37: note:   ‘std::end’
   template<typename _Tp> const _Tp* end(const valarray<_Tp>&);
                                     ^~~
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/src/PluginServiceV2.cpp:178:65: error: ‘is_regular_file’ was not declared in this scope
                   if ( p.path().extension() == ".components" && is_regular_file( p.path() ) ) {
                                                                 ^~~~~~~~~~~~~~~
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/src/PluginServiceV2.cpp:178:65: note: suggested alternative:
In file included from /usr/include/boost/filesystem.hpp:17:0,
                 from /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/src/PluginServiceV2.cpp:35:
/usr/include/boost/filesystem/operations.hpp:301:8: note:   ‘boost::filesystem::is_regular_file’
   bool is_regular_file(const path& p, system::error_code& ec)
        ^~~~~~~~~~~~~~~
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/src/PluginServiceV2.cpp:182:53: error: no matching function for call to ‘std::basic_ifstream<char>::basic_ifstream(<brace-enclosed initializer list>)’
                     std::ifstream factories{fullPath};
                                                     ^
In file included from /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/src/PluginServiceV2.cpp:21:0:
/cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/fstream:521:7: note: candidate: std::basic_ifstream<_CharT, _Traits>::basic_ifstream(std::basic_ifstream<_CharT, _Traits>&&) [with _CharT = char; _Traits = std::char_traits<char>]
       basic_ifstream(basic_ifstream&& __rhs)
       ^~~~~~~~~~~~~~
/cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/fstream:521:7: note:   conversion of argument 1 would be ill-formed:
/cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/fstream:511:7: note: candidate: std::basic_ifstream<_CharT, _Traits>::basic_ifstream(const string&, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::__cxx11::string = std::__cxx11::basic_string<char>; std::ios_base::openmode = std::_Ios_Openmode]
       basic_ifstream(const std::string& __s,
       ^~~~~~~~~~~~~~
/cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/fstream:511:7: note:   conversion of argument 1 would be ill-formed:
/cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/fstream:495:7: note: candidate: std::basic_ifstream<_CharT, _Traits>::basic_ifstream(const char*, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::_Ios_Openmode]
       basic_ifstream(const char* __s, ios_base::openmode __mode = ios_base::in)
       ^~~~~~~~~~~~~~
/cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/fstream:495:7: note:   conversion of argument 1 would be ill-formed:
/cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/fstream:481:7: note: candidate: std::basic_ifstream<_CharT, _Traits>::basic_ifstream() [with _CharT = char; _Traits = std::char_traits<char>]
       basic_ifstream() : __istream_type(), _M_filebuf()
       ^~~~~~~~~~~~~~
/cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/fstream:481:7: note:   candidate expects 0 arguments, 1 provided
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-return-type-c-linkage’
cc1plus: warning: unrecognized command line option ‘-Wno-keyword-macro’
make[2]: *** [GaudiPluginService/CMakeFiles/DD4hepGaudiPluginMgr.dir/src/PluginServiceV2.cpp.o] Error 1
make[1]: *** [GaudiPluginService/CMakeFiles/DD4hepGaudiPluginMgr.dir/all] Error 2
make: *** [all] Error 2
```

I'll try to re-build Geant4 tomorrow with this TLS option and try both v01-10 and master versions.

**Comment by petricm** [comment]
Can you post the cmake configure step output also

**Comment by MarkusFrankATcernch** [comment]
Remi,
I am not sure, but I suspect you need gcc 8 or higher.  
Could you give this a try?
I think I remember similar issues when moving to the new plugin manager.

**Comment by petricm** [comment]
No, we are testing with gcc 6.2 and 7.3 and C++14 and it works.

**Comment by rete** [comment]
CMake configure step:

```shell
$ cmake -DDD4HEP_USE_GEANT4=ON -DDD4HEP_USE_LCIO=OFF -DDD4HEP_USE_BOOST=ON -DCMAKE_CXX_STANDARD=17 ../master
-- CMAKE_INSTALL_PREFIX is /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master - overwrite with -D CMAKE_INSTALL_PREFIX
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Found LATEX: /usr/bin/latex   
-- No LaTeX/Biber found, cannot compile user manual.
-- The CXX compiler identification is GNU 7.3.0
-- Check for working CXX compiler: /cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/bin/g++
-- Check for working CXX compiler: /cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Will be building these packages: DDRec;DDDetectors;DDCond;DDAlign;DDDigi;DDG4;DDEve;UtilityApps
-- Including DD4hepBuild.cmake
-- The C compiler identification is GNU 7.3.0
-- Check for working C compiler: /cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/bin/gcc
-- Check for working C compiler: /cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- DD4hep_configure_output: set CMAKE_INSTALL_PREFIX to /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master
-- Boost version: 1.53.0
-- |++> Compiler does not have filesystem support, falling  back to Boost::filesystem
-- Boost version: 1.53.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Performing Test CXX_FLAG_WORKS__Wall
-- Performing Test CXX_FLAG_WORKS__Wall - Success
-- Performing Test CXX_FLAG_WORKS__Wextra
-- Performing Test CXX_FLAG_WORKS__Wextra - Success
-- Performing Test CXX_FLAG_WORKS__pedantic
-- Performing Test CXX_FLAG_WORKS__pedantic - Success
-- Performing Test CXX_FLAG_WORKS__Wshadow
-- Performing Test CXX_FLAG_WORKS__Wshadow - Success
-- Performing Test CXX_FLAG_WORKS__Wformat_security
-- Performing Test CXX_FLAG_WORKS__Wformat_security - Success
-- Performing Test CXX_FLAG_WORKS__Wno_long_long
-- Performing Test CXX_FLAG_WORKS__Wno_long_long - Success
-- Performing Test CXX_FLAG_WORKS__Wdeprecated
-- Performing Test CXX_FLAG_WORKS__Wdeprecated - Success
-- Performing Test CXX_FLAG_WORKS__fdiagnostics_color=auto
-- Performing Test CXX_FLAG_WORKS__fdiagnostics_color=auto - Success
-- Performing Test CXX_FLAG_WORKS_FTLS_global_dynamic
-- Performing Test CXX_FLAG_WORKS_FTLS_global_dynamic - Success
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- |> Building GaudiPluginService
-- |> Building DDParsers
-- |++> Will build DDParsers
-- |> Building DDCore
-- |++> Will be Building DDCore
-- |++++> Building dictionary ... G__DD4hep
-- |++++> Building dictionary ... G__DD4hepGeo
-- |++++> Building dictionary ... G__DD4hepProperties
-- |++++> Building dictionary ... G__DD4hepSegmentations
-- |++> Boost available, building Json Parsers
-- |++> Building Plugin: DDCorePlugins
-- |++> Found Root::GDML: Creating DDGDMLPlugins
-- |++> Building Plugin: DDGDMLPlugins
-- |++> Building Plugin: DDPythonPlugins
-- |> Building DDRec
-- |++> Will build DDRec
-- |++++> Building dictionary ... G__DDRec
-- |++> Building Plugin: DDRecPlugins
-- |> Building DDDetectors
-- |++> Building Plugin: DDDetectors
-- |> Building DDCond
-- |++++> Building dictionary ... G__DDCond
-- |++> Building Plugin: DDCondPlugins
-- |> Building DDAlign
-- |++> Building Plugin: DDAlignPlugins
-- |> Building DDDigi
-- |++> TBB not found. DDDigi will only work single threaded.
-- |++++> Building dictionary ... G__DDDigi
-- |++> Building Plugin: DDDigiPlugins
-- |> Building DDG4
-- |++> Building Plugin: DDG4Legacy
-- |++++> Building dictionary ... G__DDG4
-- |++> Building Plugin: DDG4Plugins
-- Found Python: /usr/lib64/libpython3.6m.so (found version "3.6.8") found components:  Development 
-- |++> Python found, creating DDG4Python Dictionary
-- |++++> Building dictionary ... G__DDG4Python
-- |++++> Building dictionary ... G__DDPython
-- |++> ROOT Has Python, creating DDPython library and plugins
-- |++> Building Plugin: DDG4Python
-- |> Building DDEve
-- |++++> Building dictionary ... G__DDEve
-- |++> Building Plugin: DDEvePlugins
-- |++++> Building dictionary ... G__DDG4IO
-- |> Building UtilityApps
-- |++++> Building dictionary ... G__eve
-- |++> Enable CTest environment....BUILD:ON 
-- 
-- -------------------------------------------------------------------------------
-- Change values with: cmake -D<Variable>=<Value>
-- CMAKE_INSTALL_PREFIX = /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master
-- CMAKE_BUILD_TYPE = RelWithDebInfo
-- CMAKE_CXX_FLAGS = -ftls-model=global-dynamic -fdiagnostics-color=auto -Wdeprecated -Wno-long-long -Wformat-security -Wshadow -pedantic -Wextra -Wall           -pthread
-- CMAKE_CXX_STANDARD = 17
-- CMAKE_SHARED_LINKER_FLAGS =  -pthread -Wl,--no-undefined
-- BUILD_TESTING = ON
-- CMAKE_MODULE_PATH =
--    /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/cmake;
-- -------------------------------------------------------------------------------
-- 
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    DD4HEP_USE_BOOST


-- Build files have been written to: /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/build_master
```

I'll give it a try with gcc 8 too

**Comment by andresailer** [comment]
Can you also run `make VERBOSE=1 -j1` and post the output until the first error shows up?

**Comment by petricm** [comment]
and `DD4HEP_USE_BOOST` is useless you have to use `Boost_NO_BOOST_CMAKE=ON` if at all

**Comment by rete** [comment]
## make verbose=1 test

```shell
$ make VERBOSE=1
/cvmfs/sft.cern.ch/lcg/releases/CMake/3.14.3-34449/x86_64-centos7-gcc7-opt/bin/cmake -S/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master -B/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/build_master --check-build-system CMakeFiles/Makefile.cmake 0
/cvmfs/sft.cern.ch/lcg/releases/CMake/3.14.3-34449/x86_64-centos7-gcc7-opt/bin/cmake -E cmake_progress_start /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/build_master/CMakeFiles /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/build_master/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/build_master'
make -f GaudiPluginService/CMakeFiles/DD4hepGaudiPluginMgr.dir/build.make GaudiPluginService/CMakeFiles/DD4hepGaudiPluginMgr.dir/depend
make[2]: Entering directory `/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/build_master'
cd /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/build_master && /cvmfs/sft.cern.ch/lcg/releases/CMake/3.14.3-34449/x86_64-centos7-gcc7-opt/bin/cmake -E cmake_depends "Unix Makefiles" /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/build_master /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/build_master/GaudiPluginService /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/build_master/GaudiPluginService/CMakeFiles/DD4hepGaudiPluginMgr.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/build_master'
make -f GaudiPluginService/CMakeFiles/DD4hepGaudiPluginMgr.dir/build.make GaudiPluginService/CMakeFiles/DD4hepGaudiPluginMgr.dir/build
make[2]: Entering directory `/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/build_master'
[  0%] Building CXX object GaudiPluginService/CMakeFiles/DD4hepGaudiPluginMgr.dir/src/PluginServiceV1.cpp.o
cd /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/build_master/GaudiPluginService && /cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/bin/g++  -DDD4hepGaudiPluginMgr_EXPORTS -DGaudi=DD4hep_Flavor -DUSE_BOOST_FILESYSTEM -I/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService  -ftls-model=global-dynamic -fdiagnostics-color=auto -Wdeprecated -Wno-long-long -Wformat-security -Wshadow -pedantic -Wextra -Wall           -pthread -O2 -g -DNDEBUG -fPIC   -Wno-shadow -Wno-unused -Wno-unused-parameter -Wno-deprecated -Wno-keyword-macro -Wno-return-type-c-linkage -std=c++1z -o CMakeFiles/DD4hepGaudiPluginMgr.dir/src/PluginServiceV1.cpp.o -c /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/src/PluginServiceV1.cpp
[  0%] Building CXX object GaudiPluginService/CMakeFiles/DD4hepGaudiPluginMgr.dir/src/PluginServiceV2.cpp.o
cd /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/build_master/GaudiPluginService && /cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/bin/g++  -DDD4hepGaudiPluginMgr_EXPORTS -DGaudi=DD4hep_Flavor -DUSE_BOOST_FILESYSTEM -I/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService  -ftls-model=global-dynamic -fdiagnostics-color=auto -Wdeprecated -Wno-long-long -Wformat-security -Wshadow -pedantic -Wextra -Wall           -pthread -O2 -g -DNDEBUG -fPIC   -Wno-shadow -Wno-unused -Wno-unused-parameter -Wno-deprecated -Wno-keyword-macro -Wno-return-type-c-linkage -std=c++1z -o CMakeFiles/DD4hepGaudiPluginMgr.dir/src/PluginServiceV2.cpp.o -c /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/src/PluginServiceV2.cpp
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/src/PluginServiceV2.cpp: In member function ‘void DD4hep_Flavor::PluginService::v2::Details::Registry::initialize()’:
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/src/PluginServiceV2.cpp:177:65: error: ‘begin’ was not declared in this scope
                 for ( auto& p : fs::directory_iterator( dirName ) ) {
                                                                 ^
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/src/PluginServiceV2.cpp:177:65: note: suggested alternative:
In file included from /cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/string:51:0,
                 from /cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/stdexcept:39,
                 from /cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/array:39,
                 from /cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/tuple:39,
                 from /cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/functional:54,
                 from /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/Gaudi/Details/PluginServiceDetailsV2.h:29,
                 from /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/Gaudi/PluginServiceV2.h:17,
                 from /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/Gaudi/PluginService.h:20,
                 from /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/src/PluginServiceV2.cpp:15:
/cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/bits/range_access.h:105:37: note:   ‘std::begin’
   template<typename _Tp> const _Tp* begin(const valarray<_Tp>&);
                                     ^~~~~
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/src/PluginServiceV2.cpp:177:65: error: ‘end’ was not declared in this scope
                 for ( auto& p : fs::directory_iterator( dirName ) ) {
                                                                 ^
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/src/PluginServiceV2.cpp:177:65: note: suggested alternative:
In file included from /cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/string:51:0,
                 from /cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/stdexcept:39,
                 from /cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/array:39,
                 from /cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/tuple:39,
                 from /cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/functional:54,
                 from /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/Gaudi/Details/PluginServiceDetailsV2.h:29,
                 from /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/Gaudi/PluginServiceV2.h:17,
                 from /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/Gaudi/PluginService.h:20,
                 from /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/src/PluginServiceV2.cpp:15:
/cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/bits/range_access.h:107:37: note:   ‘std::end’
   template<typename _Tp> const _Tp* end(const valarray<_Tp>&);
                                     ^~~
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/src/PluginServiceV2.cpp:178:65: error: ‘is_regular_file’ was not declared in this scope
                   if ( p.path().extension() == ".components" && is_regular_file( p.path() ) ) {
                                                                 ^~~~~~~~~~~~~~~
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/src/PluginServiceV2.cpp:178:65: note: suggested alternative:
In file included from /usr/include/boost/filesystem.hpp:17:0,
                 from /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/src/PluginServiceV2.cpp:35:
/usr/include/boost/filesystem/operations.hpp:301:8: note:   ‘boost::filesystem::is_regular_file’
   bool is_regular_file(const path& p, system::error_code& ec)
        ^~~~~~~~~~~~~~~
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/src/PluginServiceV2.cpp:182:53: error: no matching function for call to ‘std::basic_ifstream<char>::basic_ifstream(<brace-enclosed initializer list>)’
                     std::ifstream factories{fullPath};
                                                     ^
In file included from /nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/GaudiPluginService/src/PluginServiceV2.cpp:21:0:
/cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/fstream:521:7: note: candidate: std::basic_ifstream<_CharT, _Traits>::basic_ifstream(std::basic_ifstream<_CharT, _Traits>&&) [with _CharT = char; _Traits = std::char_traits<char>]
       basic_ifstream(basic_ifstream&& __rhs)
       ^~~~~~~~~~~~~~
/cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/fstream:521:7: note:   conversion of argument 1 would be ill-formed:
/cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/fstream:511:7: note: candidate: std::basic_ifstream<_CharT, _Traits>::basic_ifstream(const string&, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::__cxx11::string = std::__cxx11::basic_string<char>; std::ios_base::openmode = std::_Ios_Openmode]
       basic_ifstream(const std::string& __s,
       ^~~~~~~~~~~~~~
/cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/fstream:511:7: note:   conversion of argument 1 would be ill-formed:
/cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/fstream:495:7: note: candidate: std::basic_ifstream<_CharT, _Traits>::basic_ifstream(const char*, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::_Ios_Openmode]
       basic_ifstream(const char* __s, ios_base::openmode __mode = ios_base::in)
       ^~~~~~~~~~~~~~
/cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/fstream:495:7: note:   conversion of argument 1 would be ill-formed:
/cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/fstream:481:7: note: candidate: std::basic_ifstream<_CharT, _Traits>::basic_ifstream() [with _CharT = char; _Traits = std::char_traits<char>]
       basic_ifstream() : __istream_type(), _M_filebuf()
       ^~~~~~~~~~~~~~
/cvmfs/sft.cern.ch/lcg/releases/gcc/7.3.0-cb1ee/x86_64-centos7/include/c++/7.3.0/fstream:481:7: note:   candidate expects 0 arguments, 1 provided
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-return-type-c-linkage’
cc1plus: warning: unrecognized command line option ‘-Wno-keyword-macro’
make[2]: *** [GaudiPluginService/CMakeFiles/DD4hepGaudiPluginMgr.dir/src/PluginServiceV2.cpp.o] Error 1
make[2]: Leaving directory `/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/build_master'
make[1]: *** [GaudiPluginService/CMakeFiles/DD4hepGaudiPluginMgr.dir/all] Error 2
make[1]: Leaving directory `/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/build_master'
make: *** [all] Error 2
```

**Comment by rete** [comment]
With gcc8 the plugin manager compiles, but I have the issue with the components file. I'll try now to recompile Geant4 with the TLS option you suggested

**Comment by andresailer** [comment]
Maybe a problem of the boost version or installation then. With gcc8 the plugin manager uses the compilers filesystem implementation.

**Comment by andresailer** [comment]
Where do you get boost from?

**Comment by rete** [comment]
Pre-installed on the machine, not by hand

**Comment by andresailer** [comment]
"begin" was only added for directory_iterator in boost 1.56
https://github.com/boostorg/filesystem/blob/06dde1a832b44a219286df1dca33c48f728e0f99/include/boost/filesystem/operations.hpp#L837-L843
```c++
  //  begin() and end() are only used by a range-based for statement in the context of
  //  auto - thus the top-level const is stripped - so returning const is harmless and
  //  emphasizes begin() is just a pass through.
  inline
  const directory_iterator& begin(const directory_iterator& iter)  {return iter;}
  inline
directory_iterator end(const directory_iterator&) {return directory_iterator();}
```

(compare with 1.55 or whatever and look for begin)

**Comment by rete** [comment]
What version of Boost do you recommend for the head version of DD4hep then ?

**Comment by andresailer** [comment]
1.62 :) 
That is what we use in our ilcsoft nightly builds

**Comment by rete** [comment]
This trial is the good one.

I tried with Geant4 10.3.2 but the HEAD version of DD4hep doesn't work anymore. I get this compilation error:

```shell
[ 59%] Building CXX object DDG4/CMakeFiles/DDG4.dir/src/Geant4Converter.cpp.o
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp: In member function ‘virtual void* dd4hep::sim::Geant4Converter::handleMaterial(const string&, dd4hep::Material) const’:
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:509:24: error: ‘class G4MaterialPropertiesTable’ has no member named ‘GetPropertyIndex’; did you mean ‘GetProperty’?
         int idx = tab->GetPropertyIndex(named->GetName(), false);
                        ^~~~~~~~~~~~~~~~
                        GetProperty
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:544:24: error: ‘class G4MaterialPropertiesTable’ has no member named ‘GetConstPropertyIndex’; did you mean ‘GetConstProperty’?
         int idx = tab->GetConstPropertyIndex(named->GetName(), false);
                        ^~~~~~~~~~~~~~~~~~~~~
                        GetConstProperty
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp: In function ‘G4OpticalSurfaceFinish geant4_surface_finish(TGeoOpticalSurface::ESurfaceFinish)’:
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:1255:18: error: ‘Rough_LUT’ was not declared in this scope
     TO_G4_FINISH(Rough_LUT);             // rough surface
                  ^~~~~~~~~
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:1217:66: note: in definition of macro ‘TO_G4_FINISH’
 #define TO_G4_FINISH(x)  case TGeoOpticalSurface::kF##x : return x;
                                                                  ^
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:1256:18: error: ‘RoughTeflon_LUT’ was not declared in this scope
     TO_G4_FINISH(RoughTeflon_LUT);       // rough surface wrapped in Teflon tape
                  ^~~~~~~~~~~~~~~
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:1217:66: note: in definition of macro ‘TO_G4_FINISH’
 #define TO_G4_FINISH(x)  case TGeoOpticalSurface::kF##x : return x;
                                                                  ^
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:1257:18: error: ‘RoughESR_LUT’ was not declared in this scope
     TO_G4_FINISH(RoughESR_LUT);          // rough surface wrapped with ESR
                  ^~~~~~~~~~~~
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:1217:66: note: in definition of macro ‘TO_G4_FINISH’
 #define TO_G4_FINISH(x)  case TGeoOpticalSurface::kF##x : return x;
                                                                  ^
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:1258:18: error: ‘RoughESRGrease_LUT’ was not declared in this scope
     TO_G4_FINISH(RoughESRGrease_LUT);    // rough surface wrapped with ESR and coupled with opical grease
                  ^~~~~~~~~~~~~~~~~~
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:1217:66: note: in definition of macro ‘TO_G4_FINISH’
 #define TO_G4_FINISH(x)  case TGeoOpticalSurface::kF##x : return x;
                                                                  ^
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:1259:18: error: ‘Polished_LUT’ was not declared in this scope
     TO_G4_FINISH(Polished_LUT);          // polished surface
                  ^~~~~~~~~~~~
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:1217:66: note: in definition of macro ‘TO_G4_FINISH’
 #define TO_G4_FINISH(x)  case TGeoOpticalSurface::kF##x : return x;
                                                                  ^
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:1259:18: note: suggested alternative: ‘polishedair’
     TO_G4_FINISH(Polished_LUT);          // polished surface
                  ^~~~~~~~~~~~
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:1217:66: note: in definition of macro ‘TO_G4_FINISH’
 #define TO_G4_FINISH(x)  case TGeoOpticalSurface::kF##x : return x;
                                                                  ^
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:1260:18: error: ‘PolishedTeflon_LUT’ was not declared in this scope
     TO_G4_FINISH(PolishedTeflon_LUT);    // polished surface wrapped in Teflon tape
                  ^~~~~~~~~~~~~~~~~~
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:1217:66: note: in definition of macro ‘TO_G4_FINISH’
 #define TO_G4_FINISH(x)  case TGeoOpticalSurface::kF##x : return x;
                                                                  ^
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:1260:18: note: suggested alternative: ‘polishedteflonair’
     TO_G4_FINISH(PolishedTeflon_LUT);    // polished surface wrapped in Teflon tape
                  ^~~~~~~~~~~~~~~~~~
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:1217:66: note: in definition of macro ‘TO_G4_FINISH’
 #define TO_G4_FINISH(x)  case TGeoOpticalSurface::kF##x : return x;
                                                                  ^
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:1261:18: error: ‘PolishedESR_LUT’ was not declared in this scope
     TO_G4_FINISH(PolishedESR_LUT);       // polished surface wrapped with ESR
                  ^~~~~~~~~~~~~~~
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:1217:66: note: in definition of macro ‘TO_G4_FINISH’
 #define TO_G4_FINISH(x)  case TGeoOpticalSurface::kF##x : return x;
                                                                  ^
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:1262:18: error: ‘PolishedESRGrease_LUT’ was not declared in this scope
     TO_G4_FINISH(PolishedESRGrease_LUT); // polished surface wrapped with ESR and coupled with opical grease
                  ^~~~~~~~~~~~~~~~~~~~~
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:1217:66: note: in definition of macro ‘TO_G4_FINISH’
 #define TO_G4_FINISH(x)  case TGeoOpticalSurface::kF##x : return x;
                                                                  ^
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:1263:18: error: ‘Detector_LUT’ was not declared in this scope
     TO_G4_FINISH(Detector_LUT);          // polished surface with optical grease
                  ^~~~~~~~~~~~
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:1217:66: note: in definition of macro ‘TO_G4_FINISH’
 #define TO_G4_FINISH(x)  case TGeoOpticalSurface::kF##x : return x;
                                                                  ^
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:1263:18: note: suggested alternative: ‘dielectric_LUT’
     TO_G4_FINISH(Detector_LUT);          // polished surface with optical grease
                  ^~~~~~~~~~~~
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:1217:66: note: in definition of macro ‘TO_G4_FINISH’
 #define TO_G4_FINISH(x)  case TGeoOpticalSurface::kF##x : return x;
                                                                  ^
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp: In function ‘G4SurfaceType geant4_surface_type(TGeoOpticalSurface::ESurfaceType)’:
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:1278:16: error: ‘dielectric_LUTDAVIS’ was not declared in this scope
     TO_G4_TYPE(dielectric_LUTDAVIS);   // dielectric-Look-Up-Table DAVIS interface
                ^~~~~~~~~~~~~~~~~~~
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:1273:64: note: in definition of macro ‘TO_G4_TYPE’
 #define TO_G4_TYPE(x)  case TGeoOpticalSurface::kT##x : return x;
                                                                ^
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:1278:16: note: suggested alternative: ‘dielectric_LUT’
     TO_G4_TYPE(dielectric_LUTDAVIS);   // dielectric-Look-Up-Table DAVIS interface
                ^~~~~~~~~~~~~~~~~~~
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:1273:64: note: in definition of macro ‘TO_G4_TYPE’
 #define TO_G4_TYPE(x)  case TGeoOpticalSurface::kT##x : return x;
                                                                ^
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp: In function ‘G4OpticalSurfaceModel geant4_surface_model(TGeoOpticalSurface::ESurfaceModel)’:
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:1296:17: error: ‘DAVIS’ was not declared in this scope
     TO_G4_MODEL(DAVIS);    // DAVIS model
                 ^~~~~
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:1291:65: note: in definition of macro ‘TO_G4_MODEL’
 #define TO_G4_MODEL(x)  case TGeoOpticalSurface::kM##x : return x;
                                                                 ^
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp: In member function ‘void* dd4hep::sim::Geant4Converter::handleOpticalSurface(TObject*) const’:
/nfs/dust/ilc/group/ild/MarlinMT/DD4hep/master/DDG4/src/Geant4Converter.cpp:1339:22: error: ‘class G4MaterialPropertiesTable’ has no member named ‘GetPropertyIndex’; did you mean ‘GetProperty’?
       int idx = tab->GetPropertyIndex(named->GetName(), false);
                      ^~~~~~~~~~~~~~~~
                      GetProperty
make[2]: *** [DDG4/CMakeFiles/DDG4.dir/src/Geant4Converter.cpp.o] Erreur 1
make[1]: *** [DDG4/CMakeFiles/DDG4.dir/all] Erreur 2
make: *** [all] Erreur 2
``` 
It looks like you are trying to use new functions from a newer version of Geant4. You should require a higher version of Geant4 in your CMakeLists.txt.

By the way, I tried to go back to DD4hep v01-10 using Geant4 v10.3.2 and I got no problem this time.

**The problem seems to be a change in Geant4 between v10.3.2 and v10.5.1**

I went through your TravisCI scripts and builds but I couldn't find any information on the Geant4 version you are using. Did you try with v10.5.1 ?

**Comment by andresailer** [comment]
The code where you get the errors is only compiled for root > 6.17, so it also depends on which root version you use when compiling.

**Comment by rete** [comment]
I use ROOT 6.18.04 in all cases. 
I kept this ROOT version and downgraded Geant4 to v10.4.3. 
Compilation and components file generation worked out. 
The issue is there only for Geant4 >= v10.5.0

**Comment by andresailer** [comment]
Root 6.18.04 and geant4 10.5.1 is what we use in travis via LCG_96 http://lcginfo.cern.ch/release_packages/x86_64-centos7-gcc8-dbg/96b/

**Comment by rete** [comment]
Maybe they built it with some special flags. I really use the same versions else. I'll give it a try with the Geant4 version provided in LCG.

**Comment by rete** [comment]
It compiles with the LCG version. Same Geant4 version (10.5.1). Are you able to reproduce the problem by compiling Geant4 yourself ?

**Comment by andresailer** [comment]
We use our own compilation of Geant4 10.05.p1 on macOS without problems. https://gitlab.cern.ch/CLICdp/DetectorSoftware/DD4hep/pipelines/1131187

Also I am not sure which problem you are talking about any more.

**Comment by rete** [comment]
The main issue remains that I can compile DD4hep but the component files are empty because the listcomponents calls during compilation fail. 
What are the CMake options you use to compile Geant4 on your side ? I couldn't find anything reliable in the build logs of LCG.

**Comment by petricm** [comment]
LCG uses [this](https://gitlab.cern.ch/sft/lcgcmake/blob/master/projects/CMakeLists.txt#L458-503) and we use a nearly identical version which is (modulo the paths for different versions)
```
cmake \
-DCMAKE_INSTALL_PREFIX=/cvmfs/clicdp.cern.ch/software/Geant4/10.04.p01/x86_64-slc6-llvm6-opt \
-DGEANT4_USE_GDML=ON \
-DGEANT4_BUILD_MULTITHREADED=ON \
-DGEANT4_INSTALL_DATA=ON \
-DCMAKE_BUILD_TYPE=Release \
-DXERCESC_ROOT_DIR=/cvmfs/clicdp.cern.ch/software/Xerces-C/3.2.1/x86_64-slc6-llvm6-opt \
-DGEANT4_USE_OPENGL_X11=ON \
-DGEANT4_USE_SYSTEM_CLHEP=ON \
-DCLHEP_ROOT_DIR=/cvmfs/clicdp.cern.ch/software/CLHEP/2.4.0.0/x86_64-slc6-llvm6-opt/ \
-DGEANT4_BUILD_CXXSTD=c++11 \
-DGEANT4_BUILD_TLS_MODEL=global-dynamic \
-DCMAKE_MACOSX_RPATH=ON \
../geant4.10.04.p01
```

**Comment by rete** [comment]
I tried with these options and even tried to set `-DCMAKE_BUILD_WITH_INSTALL_RPATH=ON`. In both cases it is still failing. I'm getting crazy ...

**Comment by petricm** [comment]
@rete what is the status of this? Were you able to solve the problem?

**Comment by rete** [comment]
Sorry for the late reply. I'm actually busy for CHEP. I'll give a try again with DD4hep v01-11 next week and come back to you. Thanks for the reminder

**Comment by petricm** [comment]
So I presume that this is solved, can you tell please what was the solution for you?

**Comment by rete** [comment]
This is actually not solved. We use Geant4 10.4.3 in the next release. The problem is still there with Geant4 10.5. We are currently making a new release, but I will re-investigate this after.

**Comment by rete** [comment]
If I prepare a docker image containing the issue, would that be fine ? The image might be a bit large (8-10 Gb-ish), but it might be nice to iterate over and find a solution. What do you think ?

**Comment by andresailer** [comment]
Is the problem that with Geant4 10.5 you get the zlib_stream error in listcomponents or that the compilation doesn't work?

**Comment by rete** [comment]
Yes exactly

**Comment by andresailer** [comment]
That was an "or" question?

**Comment by rete** [comment]
Haha, sorry. The ZLIB error is still there and the packages after in the stack are of course not compiling.

**Comment by andresailer** [comment]
Do you want to try building geant4 10.5 with
```
cmake  ... -D GEANT4_USE_SYSTEM_ZLIB=ON ...
```

**Comment by rete** [comment]
Hu. Didn't try that yet... Thanks. I'll give it a try.

**Comment by rete** [comment]
This seems indeed to fix the problem. the zstream errors disapeared and everything compiles fine (tested on Centos7).
This problem is not related to DD4hep itself, but to how Geant4 uses ZLIB.

Summary for potential future readers with the same issue:

## Issue 
During DD4hep compilation, the source files are correctly compiled untill the end but the component files generation fail for DD4hep Geant4 libraries only (DDG4, DDG4Legacy, etc...). 
The error message for each `listcomponent` call is:
>  fatal error: malformed or corrupted AST file: 'could not decompress embedded file contents: zlib error: Z_STREAM_ERROR'

## Current fix
Geant4 compiles its own zlib version internally by default. Passing `-DGEANT4_USE_SYSTEM_ZLIB=ON` to the Geant4 CMake command before building seems to fix the issue on my side.
